### ISSUE TITLE
Panic error - not working

### ISSUE THREAD

**Issue by codeyash** [ryanisaacg/elefont#13]
Machines: M1 Apple Macbook pro
Rust: 1.54.0-nightly

The Fontdue and Rusttype both are not working.

Thread 'main' panicked at 'Failed to save file: Unsupported(UnsupportedError { format: Exact(Png), kind: Format(Exact(Png)) })', examples/render_image.rs:28:10
stack backtrace:
   0: rust_begin_unwind
             at /rustc/625d5a693e4697bcafdd34fd1a38c281acabb8e9/library/std/src/panicking.rs:515:5
   1: core::panicking::panic_fmt
             at /rustc/625d5a693e4697bcafdd34fd1a38c281acabb8e9/library/core/src/panicking.rs:92:14
   2: core::result::unwrap_failed
             at /rustc/625d5a693e4697bcafdd34fd1a38c281acabb8e9/library/core/src/result.rs:1355:5
   3: core::result::Result<T,E>::expect
             at /rustc/625d5a693e4697bcafdd34fd1a38c281acabb8e9/library/core/src/result.rs:997:23
   4: render_image::main
             at ./examples/render_image.rs:25:5
   5: core::ops::function::FnOnce::call_once
             at /rustc/625d5a693e4697bcafdd34fd1a38c281acabb8e9/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

Process finished with exit code 101

**Comment by elliegoldstein** [comment]
Two things:

1. This library isn't really maintained, which you should be aware of if you're using it.
2. Seems like the `image` crate doesn't understand `.png`. Maybe you need to enable a feature?
